name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HG: ${{ secrets.HF_WRITE_TOKEN }}
        run: git remote add space https://ZequnZ:$HF_WRITE_TOKEN@huggingface.co/spaces/ZequnZ/Chat-with-Mistral-7B
      - name: Push to hub
        env:
          HG: ${{ secrets.HF_WRITE_TOKEN }}
        run: git push --force https://ZequnZ:$HF_WRITE_TOKEN@huggingface.co/spaces/ZequnZ/Chat-with-Mistral-7B main